config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions' }

  resources :users do
    get :badges, on: :member
  end

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member

    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  post 'send_message', to: 'application#send_message'
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule_name: { category: 0, level: 1, first_attempt: 2 }

  validates :title, :image, :rule_name, :rule_value, presence: true

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update badge_params
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find params[:id]
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule_name, :rule_value)
  end
end

app/views/admin/badges/_badge.html.erb
<tr class="align-middle">
  <td><%= link_to badge.title, admin_badge_path(badge) %></td>
  <td><%= image_tag "badges/#{badge.image}.png", width: "50" %></td>
  <td><%= badge.rule_name %></td>
  <td><%= badge.rule_value %></td>
  <td>
    <%= link_to t('actions.edit'), edit_admin_badge_path(badge), class: "btn btn-success btn-sm" %>
    <%= link_to t('actions.destroy'), admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('actions.confirm') },
                class: "btn btn-outline-danger btn-sm" %>
  </td> 
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge] do |f| %>
  <%= render 'shared/errors', resource: @badge %>

  <div class="form-group mb-4 col-6">
    <%= f.label :title, class: "form-label" %>        
    <%= f.text_field :title, class: 'form-control form-control-sm' %>
  </div>


  <div class="form-group mb-2 col-6">
    <%= f.label :image, class: "form-label" %> 
    <div class="row">
      <% 12.times do |i| %>
        <div class="col-2 mb-3">
          <%= image_tag "badges/#{i}.png", width: "70" %>
          <div class="text-center"><%= i %></div>
        </div>
      <% end %>
    </div>          
    <%= f.number_field :image,  class: 'form-control form-control-sm',
                                placeholder: t('.choose_image'),
                                min: 0, max: 11, required: true %>
  </div>

  <div class="form-group mb-2 col-6">
    <%= f.label :rule_name, class: "form-label" %>        
    <%= f.select :rule_name, Badge.rule_names.keys, { prompt: t('.choose_rule') }, class: 'form-select form-select-sm' %>
  </div>

  <div class="form-group mb-2 col-6">
    <%= f.label :rule_value, class: "form-label" %>
    <%= f.text_field :rule_value, class: 'form-control form-control-sm' %>
  </div>
  
  <div class="text-center col-6 mt-3">
    <%= f.submit class:"btn btn-primary"%>
    <%= link_to t('actions.back'), :back, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_badge') %></h1>

<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.badges') %></h1>

<%= link_to t('.new_badge'), new_admin_badge_path %><br>

<table class="table table-striped mt-3">
  <tr>
    <th><%= t('.title') %></th>
    <th><%= t('.image') %></th>
    <th><%= t('.rule_name') %></th>
    <th><%= t('.rule_value') %></th>
    <th><%= t('actions.actions') %></th>
  </tr>

  <%= render @badges %>
  
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.new_badge') %></h1>

<%= render 'form' %>

app/views/admin/badges/show.html.erb
<h1><%= t('.show_badge') %></h1>

<div class="bg-white border rounded p-4 my-4">
  <p>
    <strong><%= t('admin.badges.index.title') %></strong>
    <%= @badge.title %>
  </p>

  <p>
    <b><%= t('admin.badges.index.image') %></b><br>
    <%= image_tag "badges/#{@badge.image}.png" %>
  </p>

  <p>
    <b><%= t('admin.badges.index.rule_name') %></b>
    <%= @badge.rule_name %>
  </p>

  <p>
    <b><%= t('admin.badges.index.rule_value') %></b>
    <%= @badge.rule_value %>
  </p>
</div>

<p>
  <%= link_to t('actions.back'), :back, class: "btn btn-secondary btn-sm" %>
  <%= link_to t('actions.edit'), edit_admin_badge_path(@badge), class: "btn btn-success btn-sm" %>
  <%= link_to t('actions.destroy'), admin_badge_path(@badge),
                 method: :delete,
                 data: { confirm: t('actions.confirm') },
                 class: "btn btn-outline-danger btn-sm" %>
</p>