config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions' }

  resources :users do
    get :badges, on: :member
  end

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member

    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  post 'send_message', to: 'application#send_message'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { in: 6..350 }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :set_current_question
  before_update     :check_test_finish

  scope :successful, -> { where(successful: true) }

  def time_left
    (test.time_limit * 15) - (Time.current - created_at).to_i
  end

  def accept!(answer_ids:)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.successful = true if complete_successful?

    save!
  end

  def completed?
    current_question.nil?
  end

  def percent_correct_answers
    ((correct_questions.fdiv test.questions.count) * 100).round
  end

  def complete_successful?
    percent_correct_answers >= SUCCESS_RATIO
  end

  def number_current_question
    test.questions.order(:id).where('id < ?', current_question_id).count + 1
  end

  private

  def check_test_finish
    self.current_question = nil if time_left <= 0
  end

  def set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.nil? && test.present?
      test.questions.order(:id).first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(answer_ids: params[:answer_ids])
    
    if @test_passage.completed?
      AwardingBadgesService.call(@test_passage)
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def current_question(test_passage)
    "#{t('.question')} #{test_passage.number_current_question} / #{test_passage.test.questions.count}"
  end
end

app/views/test_passages/_progress_bar.html.erb
<div class="progress my-4">
  <%= content_tag :div, '', class: 'progress-bar',
                            data: { current_question: @test_passage.number_current_question,
                            questions_count: @test_passage.test.questions.count } %>
</div>

app/views/test_passages/_result_message.html.erb
<% if @test_passage.complete_successful? %>
  <div class="success_result">
    <%= t('.success_result', result: @test_passage.percent_correct_answers) %>
  </div>
<% else %>
  <div class="fail_result">
    <%= t('.fail_result', result: @test_passage.percent_correct_answers) %>
  </div>
<% end %>

app/views/test_passages/_timer.html.erb
  <%= t('.time_left') %>
  
  <%= content_tag :div, id: 'timer', data: { test_passage_id: @test_passage.id } do %>    
    <%= @test_passage.time_left %>
  <% end %>

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<%= render 'result_message' %>

<%= link_to t('actions.all_tests'), tests_path, class: "btn btn-success mt-2" %>
<%= button_to t('.restart'), start_test_path(@test_passage.test), class: "btn btn-primary mt-2" %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<%= render 'progress_bar' %>

<p><%= current_question(@test_passage) %></p>

<%= render 'timer' if @test_passage.test.has_time_limit? %>

<div class="mb-3">
  <b><%= @test_passage.current_question.body %></b>
</div>

<%= form_with url: test_passage_path(@test_passage), method: :put, html: { name: "question" } do |f| %>
  <%= f.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <div class="form-check mb-2 col-6">
      <%= b.check_box class: "form-check-input" %>
      <%= b.label class: "form-check-label" %>
    </div>
  <% end %>

  <%= button_tag t('.next'), type: 'submit', class:"btn btn-primary btn-sm mt-3" %>
<% end %>

<p><%= button_to t('actions.create_gist'), test_passage_gists_path(@test_passage), class: "btn btn-success btn-sm" %></p>