config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions' }

  resources :users do
    get :badges, on: :member
  end

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member

    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  post 'send_message', to: 'application#send_message'
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div,
                  class: "resource-errors alert alert-danger alert-dismissible fade show",
                  role: "alert",
                  data: { resource_id: resource.id } do %>
    <h5><%= t('.header', count: resource.errors.count) %></h5>
    
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <% end %>


<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
    <%== message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <a href="https://github.com/newaaz" target="_blank" rel="nofollow" rel="noopener" class="nav-link px-2">Kochubey Sergey</a>
      </li>
      <li class="nav-item">
        <%= github_url("newaaz", "test-guru") %>
      </li>   
    </ul>
    <p class="text-center text-muted"><%= t('.app_for') %></p>
    <p class="text-center text-muted">
      <%= current_year %> |
      <a href="https://thinknetica.com/" target="_blank" rel="nofollow" rel="noopener">
        <%= t('.link_to_think') %>
      </a>
    </p>
  </footer>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light sticky-top" style="background-color: #dadada;">
  <div class="container">  
    <%= link_to "Test Guru", root_url, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header" style="background-color: #dadada;">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">      
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <span class="nav-link" role="button" data-bs-toggle="modal" data-bs-target="#messageModal">
            <%= octicon 'mail', class: "text-black" %>
              <%= t('.contact_us') %>
            </span>
          </li> 

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= octicon 'person', class: "text-black" %>
                <%= current_user.name %> 
              </a>
              <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                <li><%= link_to t('actions.badges'), badges_user_path(current_user), class: "dropdown-item" %></li> 
                <li><%= link_to t('actions.all_tests'), tests_path, class: "dropdown-item" %></li>                
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to t('actions.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </li>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to admin_tests_path, class: 'nav-link' do %>
                  <%= octicon 'gear', class: "text-black" %>
                  <%= t('.admin') %>
                <% end %>
              </li> 
            <% end %>
          <% else %>
            <div class="text-end mt-1">
              <%= link_to t('actions.signup'), new_user_registration_path, class: 'btn btn-sm btn-outline-primary' %>
              <%= link_to t('actions.login'), new_user_session_path, class: 'btn btn-sm btn-outline-primary' %>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<!-- message modal -->
<div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Написать нам</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="body-message">
        <%= form_with(url: send_message_path, local: false, html: { name: "message" }) do |f| %>
          <div class="form-group">
            <%= f.label "Email" %>            
            <%= f.email_field :email, class:"form-control form-control-sm", required: true %>             
          </div>      
              
          <div class="my-3">
            <%= f.label "Текст:", class: 'form-label' %>          
            <%= f.text_area :body, class:"form-control", rows:3 %>
          </div>

          <div class="d-flex justify-content-center">
            <%= button_tag "Отправить", type: 'submit', class:"w-50 btn btn-primary" %>
          </div>              
        <% end %>    
      </div>
    </div>
  </div>
</div>