config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions' }

  resources :users do
    get :badges, on: :member
  end

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member

    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  post 'send_message', to: 'application#send_message'
end

app/views/admin/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
  <div class="container">  
    <%= link_to "Test Guru (admin)", admin_tests_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header" style="background-color: #dadada;">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">      
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">              
            <%= link_to admin_badges_path, class: 'nav-link' do %>
              <%= octicon 'file-badge', class: "text-white" %>
              <%= t('actions.badges') %>
            <% end %>
          </li>  
          <li class="nav-item">              
            <%= link_to admin_gists_path, class: 'nav-link' do %>
              <%= octicon 'file', class: "text-white" %>
              <%= t('actions.gists') %>
            <% end %>
          </li>  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= octicon 'gear', class: "text-white" %>
              <%= t('shared.nav.admin') %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
              <li><%= link_to t('shared.nav.all_tests_admin'), admin_tests_path, class: "dropdown-item" %></li>
              <li><%= link_to t('admin.tests.index.new_test'), new_admin_test_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to t('actions.all_tests'), tests_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to t('actions.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>